### PR TITLE
Adding "stash" functionality

### PR DESCRIPTION
**Pull request by alexhstone**
I caught a bug in my handling of the "get random person" route.  This version addresses that bug.  

My handling of the "stash" post request may need a little fiddling with though.

### CODE REVIEW

**Comment by rapPayne** [comment]
You said you didn't test it. Would you like some help testing? Let me know and we'll do it together. :-)

index.js and index.html
It isn't a good idea to store state in the UI. In other words, don't store the stashed person in currentPerson.dataset.id. Instead just grab the person's Id from currentPerson.id. (Line 69).

thereIsACurrentPerson function is a good idea. It can just look at the currentPerson. If they're truthy, they exist. If not, they don't.

server.js...
Line 24 is a reference copy. Use array spread. ie. unchosenPeople = [...stashed].
In app.get('/people/unchosen'), youre adding stashed to unchosed (really nice use of spread, BTW), but this will result in the stashed people appearing in the same section as unchosen people with no visual differentiation. Can we just keep them separate? We're returning A) currentPerson, B) chosenPeople, and C) unchosenPeople with every action. Please just add a D) stashedPeople to that. You'll provided the endpoint at GET /people/stashed.

**Comment by rapPayne** [comment]
p.s. If you have an active PR, you can just make changes, add/commit/push and the PR sees your latest commits. No need to close a PR and create a new one. Cool, right?

**Comment by alexhstone** [comment]
Would absolutely like some help with testing!  I know how to do unit tests in Java but I haven't written many for JS.  

Thank you for the feedback!  All of these comments make sense.   My original thought with the stashing is that it'd be kind of "behind the scenes" and the user wouldn't necessarily need to know that the stashed users were in a separate queue but I can see how that might be a confusing experience.

**Comment by rapPayne** [comment]
When you said "didn't test" I thought you meant you didn't even run it. You're fine. (But I'm happy to help some other time with unit testing.) Long story short, you'll use Jest for the unit tests.

I'll look forward to you implementing my suggestions. If you want to pair program on this, let me know. Happy to do that with you. It'd be fun.

**Review by Nissi126 — CHANGES_REQUESTED** [review]
Just a couple of changes from my first scan of the code. Ill pull it down and run it locally on Monday to check for bugs.

**Comment by rapPayne** [comment]
Nadia completed this issue. Although Alex had it 90% solved himself.

**Pull request closed without merging**
